name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-and-scan:
    runs-on: ubuntu-latest   # must be indented 2 spaces under job name

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
         
      - name: 'Build and start all services'
        run: docker-compose up -d --build

      - name: 'Wait for services'
        run: |
          until pg_isready -h localhost -U user -d testdb; do
            echo "Waiting for Postgres..."
            sleep 2
              done
            echo "Postgres is ready!"

      - name: backend 
        run: |
          docker-compose exec -T backend npm test

      - name: frontend 
        run:  |
          docker-compose build frontend
          docker-compose up -d frontend

      - name: frontend vulnerability scan with trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: image
          image-ref: frontend:latest
          ignore-unfixed: true
          format: json
          output: report/trivy-frontend.json
          exit-code: 1
          severity: HIGH,CRITICAL
            
     - name: backend vulnerability scan with trivy
       uses: aquasecurity/trivy-action@0.24.0
       with:
          scan-type: image
          image-ref: backend:latest
          ignore-unfixed: true
          format: json
          output: report/trivy-backend.json
          exit-code: 1
          severity: HIGH,CRITICAL 
 
      - name: Upload Trivy scan reports
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: reports/    

      - name: Tear down containers
        if: always()
        run: docker-compose down -v          
