name: CI workflow

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: Build images
        run: docker-compose build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Run backend tests
        run: docker-compose run --rm backend npm test
      - name: Run frontend tests
        run: docker-compose run --rm frontend npm test                                                                                                                                                                                                                                                                    trivy:                                                                                                                                                        runs-on: ubuntu-latest                                                                                                                                      needs: build                                                                                                                                                steps:                                                                                                                                                        - uses: actions/checkout@v3                                                                                                                                 - name: Run Trivy scan                                                                                                                                        uses: aquasecurity/trivy-action@master                                                                                                                      with:                                                                                                                                                         image-ref: backend:latest                                                                                                                                   severity: HIGH,CRITICAL                                                                                                                                     exit-code: 1                                                                                                                                            - name: Run Trivy scan (frontend)                                                                                                                             uses: aquasecurity/trivy-action@master
        with:
          image-ref: frontend:latest
          severity: HIGH,CRITICAL
          exit-code: 1

  sonarqube:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_HOST_URL: http://sonarqube:9000
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
